openapi: 3.0.1
info:
  title: MavenTestAPI
  description: API Definition of MavenTestAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/maventest
paths:
  /:
    get:
      responses:
        default:
          description: Default response
